# Generated by Django 2.1.7 on 2019-02-24 07:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('nairobi', django.db.models.manager.Manager()),
            ],
        ),
    ]
