# Generated by Django 2.1.5 on 2019-02-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='Notes',
        ),
    ]
