# Generated by Django 2.1.5 on 2019-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesap', '0002_auto_20190206_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
