# Generated by Django 2.1.5 on 2019-02-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesap', '0003_auto_20190206_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created']},
        ),
    ]
